apiVersion: v1
kind: Pod
metadata: 
  name: kube-app
  labels:
   app: kube-app
spec:
  containers:
   - name: kube-app
     image: srdavidsilva/sr2ds:dockerize-vuejs-app
     ports:
     - containerPort: 8080
